sourceDir     = "source"
destDir       = "public"
postsDir      = "source/_posts"
postLayoutsDir = "source/_post_layouts"

[Site]
Title = "Your Blog Title"
Author = "Your Name"
Description = "A description of your blog"
